### ISSUE TITLE
`box-decoration-break` example output is hidden

### ISSUE THREAD

**Issue by hacknug** [mdn/interactive-examples#1119] opened 2018-08-31 14:11 UTC
As stated, the example for how the `box-decoration-break` property works, has the class `.hidden` on the output element. This is not good because [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) readers can not see the live example and they need to rely on the screenshots.

https://github.com/mdn/interactive-examples/blob/cc5ae0a4dd019db6eda4dd60e88be19b94e4f437/live-examples/css-examples/fragmentation/box-decoration-break.html#L17

I can submit a PR if needed. Just let me know.

**Comment by wbamberg** [comment] 2018-08-31 15:05
Thanks for filing!

I think the problem is not the "hidden" class. I think you are using a browser that does not support this property, or that needs it prefixed (https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break#Browser_compatibility).

At the moment, if this is the case, the example editor displays something like this:

<img width="601" alt="screen shot 2018-08-31 at 7 59 21 am" src="https://user-images.githubusercontent.com/432915/44920040-cb248a00-acf3-11e8-8214-cc8470e9545b.png">

Try the page in Firefox, it should look like:

<img width="747" alt="screen shot 2018-08-31 at 8 00 04 am" src="https://user-images.githubusercontent.com/432915/44920104-e8595880-acf3-11e8-9f07-c644cad5c00b.png">

I know the way we handle unsupported properties is not ideal and would love to have a better way to handle it - this is discussed at some length here: https://github.com/mdn/interactive-examples/issues/532. We have bigger priorities at the moment though, mostly because most properties are in fact well supported across browsers.

In general we've handled this by just removing the examples for properties that don't have good cross-browser support (e.g. all the [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties)). So perhaps we should do the same for `box-decoration-break` - sad though, as it is a nice example.

**Comment by hacknug** [comment] 2018-08-31 15:10
I'm using vanilla Chrome (v68.0.3440.106) and it supports the property. If I remove the `.hidden` class from the output element this is what I see:

<img width="1063" alt="captura de pantalla 2018-08-31 a las 17 09 06" src="https://user-images.githubusercontent.com/1107521/44920595-a99dbf80-ad40-11e8-8c25-0c7dcc4d0b4d.png">

**Comment by wbamberg** [comment] 2018-08-31 16:42
> I'm using vanilla Chrome (v68.0.3440.106) and it supports the property

Are you sure it supports the property, unprefixed? MDN and [Caniuse](https://caniuse.com/#search=box-decoration-break) both disagree.

> If I remove the .hidden class from the output element this is what I see:

This is expected. All the examples have `hidden` in the source (e.g. [`align-items`](https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/box-alignment/align-items.html#L31)). When the editor runs, it [checks whether the property is supported by the browser](https://github.com/mdn/interactive-examples/blob/master/js/editable-css.js#L80-L91), and if it is, [shows the output pane by removing `hidden`](https://github.com/mdn/interactive-examples/blob/master/js/editable-css.js#L15-L21).

So by changing the initial hidden state, all that happens is that this part of initialization is short-circuited. The output pane is shown, but it's not actually a usable interactive example - the releavant property hasn't been applied to the element, and you can't select different values for the property.

So this isn't a fix. We could perhaps fix this by making the property support checking more sophisticated, so it could handle prefixed properties.

At the moment property support checking works by having the example supply a `data-property` attribute whose value is the name of a CSS property, and the checker creates a `div`, tries to apply the property, and says the property is supported if the property was applied: https://github.com/mdn/interactive-examples/blob/master/js/editor-libs/mce-utils.js#L21-L39. I imagine you could patch this by letting the example supply multiple properties to test, and if any of them apply, then the property could be treated as supported. Then the example could provide both prefixed and unprefixed variants of the property:

```
box-decoration-break: slice;
-webkit-box-decoration-break: slice;
---------------------------------------
box-decoration-break: clone;
-webkit-box-decoration-break: clone;
```

One extra difficulty is that according to the support docs, Chrome also only supports this on inline elements, so the element the support checker creates needs to have `display:inline`.

**Comment by wbamberg** [comment] 2018-09-07 18:33
Fixed by https://github.com/mdn/interactive-examples/pull/1120.

**Closed by wbamberg** 2018-09-07 18:33 UTC
