### ISSUE TITLE
The live js editor can go up to 2 levels of scrollbars

### ISSUE THREAD

**Issue by JSmithOner** [mdn/interactive-examples#2053] opened 2022-03-21 09:51 UTC
When using the javascript editor with long code and long console outputs, the overflows are a bit messy, as shown on the picture.

![live editor](https://user-images.githubusercontent.com/12628841/159237521-6c2458d4-14ff-4371-b2ff-06d26295a507.png)

I was thinking of editing the style and perhaps html to make it more clear and most important get rid of the first level scrollbars ( the outer ones ). Only problem is I can't find the code in the repo. If anyone could tell me if I can make an edit of this editor and then after make a pull request. Thanks in advance.

**Comment by wbamberg** [comment] 2022-03-27 18:07
@JSmithOner , I don't see the outer scrollbar in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map , do you have steps to reproduce for it?

**Comment by wbamberg** [comment] 2022-03-27 18:08
(This does happen sometimes though, we have an issue for it at https://github.com/mdn/bob/issues/730 . So I'm not suggesting it's not a problem, just that I don't see it in this particular case.)

**Comment by JSmithOner** [comment] 2022-03-29 15:18
@wbamberg Thank you for your answer, I often use this editor to quickly test algorithms so I guess the problem don't appear with the mdn examples. Also I've been trying to clone the repo to fix this bug but looks like the editor is integrated via a sort of embedded component. Didn't took time to understand how it worked but couldn't reproduce the issue locally. The error don't occur locally because the editor fits the window's width also I guess the editor on the web is wrapped inside a div that allows overflow and maybe don't have a max width that allows container to fits it's parent div. What do you think?

**Comment by NiedziolkaMichal** [comment] 2023-02-24 19:05
This is now fixed. A lot of content in the JS example looks like this:
![image](https://user-images.githubusercontent.com/100634371/221269195-f5457d7c-a834-4e26-90e7-8f9deff501e2.png)

Thanks a lot for reporting this issue.

**Closed by NiedziolkaMichal** 2023-02-24 19:05 UTC
Labels: idle
