### ISSUE TITLE
Add Cache-Control header for static assets

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#311] opened 2017-10-25 16:02 UTC
After having a look with webpagetest and flagging it with @jwhitlock, it was determined that the "go faster" switch is not on, and so static assets for the interactive editor is not being browser cached.

https://www.webpagetest.org/result/171025_Q6_744b157b72489d1b5b246b7bb7263e3c/1/performance_optimization/

**Comment by jwhitlock** [comment] 2017-10-25 18:59
To be clear, there is no "go faster" switch. As this [serverfault page](https://serverfault.com/a/770469/3455) says, the ``Cache-Control`` header can be set two ways:

1. Set some metadata when uploading a file to S3. I'll need to research the mechanism used to populate S3 to see how to do that, and make a change that wouldn't take effect until the next deployment.
2. Use Lambda@Edge to add a header. It sounds like they've had mixed results using this for view source

**Comment by schalkneethling** [comment] 2017-10-26 06:56
Thanks for adding the details here @jwhitlock - much appreciated.

**Comment by jgmize** [comment] 2017-11-09 20:45
```
$ curl -I https://interactive-examples.mdn.mozilla.net/js/lib/codemirror.js
HTTP/1.1 200 OK
Content-Type: application/javascript
Content-Length: 164376
Connection: keep-alive
Date: Thu, 09 Nov 2017 04:18:47 GMT
Last-Modified: Wed, 08 Nov 2017 19:01:34 GMT
x-amz-version-id: ddXiskpZ.26JDknHgGGxUv733ra3VlN4
ETag: "dff919949b0a3c22570afd2bce2deef6"
Server: AmazonS3
Vary: Accept-Encoding
X-Cache: RefreshHit from cloudfront
Via: 1.1 013402c40cbbe4531879e87807cfee5d.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 6M7f-Dix_sP4aOab06tsam8fYLENWYRAWoIbj8ZuSjx-4hN4LDo9UQ==
```

**Comment by jgmize** [comment] 2017-11-09 20:54
Note that the cache-control header is set at the origin:
```
$ curl -I mdninteractive.s3-website-us-west-2.amazonaws.com/js/lib/codemirror.js
HTTP/1.1 200 OK
x-amz-id-2: RgQmOg8pbgMo09fmtbuW6xO7RvjJO5mZpqGRN0Y8WMnwGKwdonzNRkbZhRfLJ4im0miAQt+ci60=
x-amz-request-id: D3E40B68B1227ADD
Date: Thu, 09 Nov 2017 20:52:37 GMT
Cache-Control: max-age=900
Last-Modified: Thu, 09 Nov 2017 20:34:59 GMT
x-amz-version-id: w79e1RuXJyshpTZbYblo6AJ0aksaR8Xm
ETag: "dff919949b0a3c22570afd2bce2deef6"
Content-Type: application/javascript
Content-Length: 164376
Server: AmazonS3
```

**Comment by jgmize** [comment] 2017-11-09 21:06
And here's an example with the cache-control header actually being passed through from cloudfront-- my first example was still serving from the cloudfront cache and didn't include the header:

```
$ curl -I https://interactive-examples.mdn.mozilla.net/pages/js/weakset-prototype-add.html
Content-Length: 1590
Connection: keep-alive
Date: Thu, 09 Nov 2017 21:03:53 GMT
Cache-Control: max-age=900
Last-Modified: Thu, 09 Nov 2017 21:01:22 GMT
x-amz-version-id: WKfHu5VfwktjFmoI0_nBFrZ7hidIo2yo
ETag: "0f3dab9adb75d79551d810cbdf2eb940"
Server: AmazonS3
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 d8053cbdcb8a8e0d3f25f05723b00cff.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 7XnGjcyCOwAUnjddXwQdjrEC7nabxAvOsXeoH_Rf-BKnd2baqEVaOA==
```

**Comment by jwhitlock** [comment] 2017-11-09 22:22
Thanks @jgmize!

**Comment by schalkneethling** [comment] 2017-11-10 13:13
@jwhitlock @jgmize Not sure if it is just a case of things taking a while to sync to all the nodes but, running webpagetest against the editor directly(and when embedded in a page on MDN), it seems items are still not being cached:

https://www.webpagetest.org/result/171110_YW_a80d7e4e519d8e01cca0c9e4d420d081/1/performance_optimization/

**Comment by jwhitlock** [comment] 2017-11-13 15:04
I can confirm:

```
$ curl -I https://interactive-examples.mdn.mozilla.net/css/codemirror.css
HTTP/1.1 200 OK
Content-Type: text/css
Content-Length: 5948
Connection: keep-alive
Date: Wed, 08 Nov 2017 15:41:51 GMT
Last-Modified: Fri, 03 Nov 2017 16:01:19 GMT
x-amz-version-id: 517FzENAp9XDKFxXcqEPuZDvMOVRsB07
ETag: "77365f9dfd360e2255031a1a1fb791d4"
Server: AmazonS3
Vary: Accept-Encoding
Age: 58
X-Cache: Hit from cloudfront
Via: 1.1 12b95f4a8620bcfb6c85511fae926d57.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 6X-2r8G-kNzHaRcQtOCSr7Xm1oxN8YPxTOAttYc1p2CPaVWVSVdduw==
```

I suspect the new command is only setting the cache headers for changed files, looking deeper.

**Comment by jwhitlock** [comment] 2017-11-13 15:42
As @jgmize showed, the origin domain is setting ``max-age=900``. but it is not appearing in CloudFront. Reading CF docs.

**Comment by schalkneethling** [comment] 2017-11-13 16:10
> As @jgmize showed, the origin domain is setting max-age=900. but it is not appearing in CloudFront. Reading CF docs.

Thanks @jwhitlock

**Comment by jwhitlock** [comment] 2017-11-13 16:20
In the default behavior, I changed **Object Caching** from **Customize** to **Use Origin Cache Headers**. I'm waiting to see if this has an effect.

**Comment by schalkneethling** [comment] 2017-11-13 17:57
@jwhitlock seems the same as of right now: https://www.webpagetest.org/result/171113_PS_3655cc5d071f23ef39ad65300871b30b/1/performance_optimization/

Will do a test again in the morning. Thanks for looking into this.

**Comment by metadave** [comment] 2017-11-13 18:43
@jwhitlock if [your change](https://github.com/mdn/interactive-examples/issues/311#issuecomment-343971777) works and you'd like to make it permanent, the [interactive-examples Terraform](https://github.com/mozmeao/infra/blob/master/apps/mdn/interactive-examples/tf/mdninteractive.tf#L75-L134) should be updated as well. I'm fine submitting a PR for this change if you're test works.

**Comment by jwhitlock** [comment] 2017-11-13 19:15
These assets were recently removed (PR #329) 

* https://interactive-examples.mdn.mozilla.net/js/require.js
* https://interactive-examples.mdn.mozilla.net/js/codemirrorLoader.js

Some assets still have no ``Cache-Control`` header, despite the origin including them:

* https://interactive-examples.mdn.mozilla.net/css/codemirror.css
* https://interactive-examples.mdn.mozilla.net/css/editor-js.css
* https://interactive-examples.mdn.mozilla.net/media/dino.svg

Some assets are now showing the ``max-age=900``. However, WebPageTest says 15 minutes is still too short:

* https://interactive-examples.mdn.mozilla.net/js/editor-js.js
* https://interactive-examples.mdn.mozilla.net/js/lib/codemirror.js
* https://interactive-examples.mdn.mozilla.net/js/mode/javascript/javascript.js

If this was served by Django, then we'd embed a hash in the filename, and set a 1-year cache. When the file changes, the hash and the filename changes, and then clients would request the new file. I suspect some of these are third-party libraries, and we could embed a version number or download date into the filename, and use longer cache durations to make WebPageTest happy.

**Comment by jwhitlock** [comment] 2017-11-13 19:43
Things are weird. Here's the current settings in AWS:

* Object Caching: Use Origin Cache Headers
* Minimum TTL: 0
* Maximum TTL: 31536000
* Default TTL: 86400

Here's the terraform settings:
* min_ttl: 0
* max_ttl: 86400
* default_ttl: 60

My reading of the [Terraform docs](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html) is that you can't set Object Caching: Use Origin Cache Headers. That's OK, we just need to make sure the ``max_ttl`` is larger than our ``Cache-Control: max-age=600`` header, according to the [CloudFront docs](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationDownloadDist).  My reading is that with Object Caching: Customize, Minimum TTL=0 means that the Cache-Control header will be used, but that CloudFront caches for the lesser of the Cache-Control header and the Default TTL. 

With the Default TTL of 24 hours, it may have taken that long for @jgmize's changes to be reflected in the responses, so it is possible that @schalkneethling checked too soon. However, shouldn't all the assets have a ``Cache-Control`` header by now? 😕 

I'm setting AWS to match terraform:

* Object Caching: Use Origin Cache Headers
* Minimum TTL: 0
* Maximum TTL: 86400
* Default TTL: 60

**Comment by metadave** [comment] 2017-11-13 19:52
SREs invalidated the interactive-examples Cloudfront cache using `/*`.

**Comment by jwhitlock** [comment] 2017-11-13 20:53
After cache invalidation, all the endpoints identified by webpagetest.org have the ``max-age=900`` header - thanks @metadave!

I'll start looking at the code and see which of these assets could get a caching header longer than 15 minutes.

**Comment by jwhitlock** [comment] 2017-11-13 21:50
After looking at the code, I suspect @schalkneethling may be able to make these changes a lot easier than me. If I'm wrong, let me know, and I can start the next round of changes.

Webpagetest.org says:

> If the expiration is set for less 7 days you will get a warning. If the expiration is set for less than 1 hour you will get a failure.

The third-party assets, like [codemirror.js](https://github.com/mdn/interactive-examples/blob/master/js/lib/codemirror.js), could be changed to embed the file version, like ``codemirror.5.29.1.js``. This would allow us to set a cache age of a year.  Others like [editable-js.js](https://github.com/mdn/interactive-examples/blob/master/js/editable-js.js) appear to commonly change, and a 15-minute cache may be the best we can do. If this is the best we can do, I can make the code changes and submit the PR.

However. it appears we're using node to build [index.js](https://github.com/mdn/interactive-examples/blob/master/index.js), including rendering templates to set the path to the actual static files. It seems it would be possible to:

1. Calculate a hash of the contents of the asset file
2. Embed that hash in the filename
3. Update assets that refer to other assets, and 
4. Render the templates with the hashed asset names

My suspicion is that there is an existing, mature node library that does just this. However, I'm not familiar enough with the node world to easily find it. Hopefully @schalkneethling or someone else watching knows of the normal tool for this work.

Closing the bug, since we now have assets with ``Cache-Control: max-age=900``

**Closed** 2017-11-13 21:57 UTC
Labels: enhancement

**Comment by schalkneethling** [comment] 2017-11-14 12:54
> Others like editable-js.js appear to commonly change, and a 15-minute cache may be the best we can do.

@jwhitlock A 30min cache of these files will also be fine.

> Hopefully @schalkneethling or someone else watching knows of the normal tool for this work.

Will take care of it. Thanks for everyone's help @jgmize @metadave @jwhitlock

**Comment by metadave** [comment] 2017-11-14 15:12
are there any additional changes that need to be added to our Terraform provisioning?

**Comment by jwhitlock** [comment] 2017-11-15 03:39
I believe that AWS is back in sync w/ our terraform configuration, after my manual changes.  After Schalk has taken a look, we may have some further changes, but I expect that will be to the sync command(s), not to terraform.

**Comment by schalkneethling** [comment] 2017-11-15 10:42
@metadave @jwhitlock In the end, to prevent the experiment with the non-iframed editor on Kuma breaking, I added a version number to the end of the bundles that contain longer lived dependency bundles.

The files then loaded now are as follows:

codemirror-5-31-0.css
css-examples-libs-1-8-4.css
editor-js.css
editor-css.css

codemirror-5-31-0.js
css-examples-libs-1-8-4.js
editor-js.js
editor-css.js
